### ISSUE TITLE
Repeated entry in tables (SRR360776)

### ISSUE THREAD

**Issue by luispedro** [linsalrob/partie#2]
The run `SRR360776` appears twice in the tables:

```bash
$ grep SRR360776 SRA_PARTIE_DATA.txt SRA_Metagenome_Types.tsv    
...
SRA_PARTIE_DATA.txt:SRR360776   86.69725743     0       0       0.01    AMPLICON
SRA_PARTIE_DATA.txt:SRR360776   86.6972574342988        0       0       0.0100000000000051      WGS
...
SRA_Metagenome_Types.tsv:SRR360776      AMPLICON
SRA_Metagenome_Types.tsv:SRR360776      WGS
```

(removed some irrelevant matches)

Most confusingly, as you can see, once it is classified as `AMPLICON` and another time as `WGS`

**Comment by linsalrob** [comment]
I don't know why this happened, we are trying to figure out why it would have been misclassified as an `AMPLICON` sequence. 

However, we ran the classifier 100 times and it was always `WGS`, moreover, that sample is [a metatranscriptome](https://www.ncbi.nlm.nih.gov/sra/?term=SRR360776) and should be a WGS.

Fixing.

**Comment by linsalrob** [comment]
Files edited and closed.
