### ISSUE TITLE
16S db corrupted?

### ISSUE THREAD

**Issue by rdoughty10** [linsalrob/partie#7]
Hello,

I am trying to use partie and after following the installation instructions. I tried running the tool and have gotten this error:

Error: 16S database corrupted
Runing the command /home/software/miniconda3/envs/ww_env/bin/bowtie2-inspect -s .//db/16SMicrobial
/home/software/miniconda3/envs/ww_env/bin/bowtie2-inspect-s: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory

I have tried deleting and redownloading the database, but I continue to get this error. 

Just wanted to check and make sure that databses are still maintained or if I am doing something wrong?

Thanks

**Comment by linsalrob** [comment]
Hi

You are not doing anything wrong.

This is an error with `bowtie` and `conda` and the problem and [solution is described in this biostars post](https://www.biostars.org/p/494922/).

Essentially, the problem is with ` libtbb.so` versioning.
